ALTER TYPE "public"."email_type" ADD VALUE 'ADMIN_TEMPLATE';--> statement-breakpoint
CREATE TABLE "email_templates" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"key" text NOT NULL,
	"name" text NOT NULL,
	"subject_de" text NOT NULL,
	"body_de" text NOT NULL,
	"subject_en" text NOT NULL,
	"body_en" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "email_templates_key_unique" UNIQUE("key")
);
--> statement-breakpoint
ALTER TABLE "email_templates" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
INSERT INTO "email_templates" ("key", "name", "subject_de", "body_de", "subject_en", "body_en") VALUES
('order-confirmation', 'Order confirmation',
 'Ihre Auftragsbestätigung – {orderNumber}',
 E'Hallo {customerName},\n\nvielen Dank für Ihren Auftrag {orderNumber}. Wir haben ihn erhalten und bearbeiten ihn nun.\n\nVoraussichtliche Lieferung: {deliveryDate}\n\nIhr Sun Container Team',
 'Your order confirmation – {orderNumber}',
 E'Hello {customerName},\n\nthank you for your order {orderNumber}. We have received it and are now processing it.\n\nEstimated delivery: {deliveryDate}\n\nYour Sun Container team'),
('in-production', 'In production',
 'Ihr Auftrag {orderNumber} ist in Produktion',
 E'Hallo {customerName},\n\nIhr Auftrag {orderNumber} befindet sich jetzt in Produktion.\n\nVoraussichtliche Lieferung: {deliveryDate}\n\nIhr Sun Container Team',
 'Your order {orderNumber} is in production',
 E'Hello {customerName},\n\nyour order {orderNumber} is now in production.\n\nEstimated delivery: {deliveryDate}\n\nYour Sun Container team'),
('ready-to-ship', 'Ready to ship',
 'Ihr Auftrag {orderNumber} ist versandbereit',
 E'Hallo {customerName},\n\nIhr Auftrag {orderNumber} ist versandbereit und verlässt in Kürze unser Werk.\n\nVoraussichtliche Lieferung: {deliveryDate}\n\nIhr Sun Container Team',
 'Your order {orderNumber} is ready to ship',
 E'Hello {customerName},\n\nyour order {orderNumber} is ready to ship and will leave our facility shortly.\n\nEstimated delivery: {deliveryDate}\n\nYour Sun Container team'),
('shipped', 'Shipped',
 'Ihr Auftrag {orderNumber} wurde versandt',
 E'Hallo {customerName},\n\nIhr Auftrag {orderNumber} wurde versandt. Trackingnummer: {trackingNumber}.\n\nVoraussichtliche Lieferung: {deliveryDate}\n\nIhr Sun Container Team',
 'Your order {orderNumber} has shipped',
 E'Hello {customerName},\n\nyour order {orderNumber} has shipped. Tracking number: {trackingNumber}.\n\nEstimated delivery: {deliveryDate}\n\nYour Sun Container team'),
('on-the-way', 'On the way',
 'Ihr Auftrag {orderNumber} ist unterwegs',
 E'Hallo {customerName},\n\nIhr Auftrag {orderNumber} ist auf dem Weg zu Ihnen.\n\nVoraussichtliche Lieferung: {deliveryDate}\n\nIhr Sun Container Team',
 'Your order {orderNumber} is on the way',
 E'Hello {customerName},\n\nyour order {orderNumber} is on its way to you.\n\nEstimated delivery: {deliveryDate}\n\nYour Sun Container team'),
('delivered', 'Delivered',
 'Ihr Auftrag {orderNumber} wurde geliefert',
 E'Hallo {customerName},\n\nIhr Auftrag {orderNumber} wurde geliefert. Wir wünschen Ihnen viel Freude damit.\n\nIhr Sun Container Team',
 'Your order {orderNumber} has been delivered',
 E'Hello {customerName},\n\nyour order {orderNumber} has been delivered. We hope you enjoy it.\n\nYour Sun Container team'),
('delivery-delay', 'Delivery delay',
 'Aktualisierung zu Ihrer Lieferung – {orderNumber}',
 E'Hallo {customerName},\n\nleider verzögert sich die Lieferung Ihres Auftrags {orderNumber}.\n\nNeue voraussichtliche Lieferung: {deliveryDate}\n\nWir bitten um Ihr Verständnis.\n\nIhr Sun Container Team',
 'Update on your delivery – {orderNumber}',
 E'Hello {customerName},\n\nunfortunately the delivery of your order {orderNumber} is delayed.\n\nNew estimated delivery: {deliveryDate}\n\nThank you for your understanding.\n\nYour Sun Container team'),
('delivery-date-change', 'Delivery date change',
 'Neuer Liefertermin für Ihren Auftrag {orderNumber}',
 E'Hallo {customerName},\n\nder voraussichtliche Liefertermin für Ihren Auftrag {orderNumber} hat sich geändert.\n\nNeuer Termin: {deliveryDate}\n\nIhr Sun Container Team',
 'Updated delivery date for your order {orderNumber}',
 E'Hello {customerName},\n\nthe estimated delivery date for your order {orderNumber} has changed.\n\nNew date: {deliveryDate}\n\nYour Sun Container team'),
('thank-you', 'Thank you',
 'Vielen Dank für Ihren Auftrag {orderNumber}',
 E'Hallo {customerName},\n\nvielen Dank, dass Sie sich für Sun Container entschieden haben. Bei Fragen sind wir jederzeit für Sie da.\n\nIhr Sun Container Team',
 'Thank you for your order {orderNumber}',
 E'Hello {customerName},\n\nthank you for choosing Sun Container. If you have any questions, we are always here to help.\n\nYour Sun Container team'),
('general-update', 'General update',
 'Update zu Ihrem Auftrag {orderNumber}',
 E'Hallo {customerName},\n\nwir möchten Sie über Ihren Auftrag {orderNumber} auf dem Laufenden halten.\n\nVoraussichtliche Lieferung: {deliveryDate}\n\nIhr Sun Container Team',
 'Update on your order {orderNumber}',
 E'Hello {customerName},\n\nwe want to keep you up to date on your order {orderNumber}.\n\nEstimated delivery: {deliveryDate}\n\nYour Sun Container team')
ON CONFLICT ("key") DO NOTHING;